'use client';
import { useState } from 'react';
import { AnalysisCase, apiBase, Suppression } from '../lib';
import { AppShell, Modal, PageTitle, useOperations } from '../ui';

export default function RulesPage(){
 const {data,reload}=useOperations();
 const [suppressOpen,setSuppressOpen]=useState(false),[backtestOpen,setBacktestOpen]=useState(false);
 const [selectedWindow,setSelectedWindow]=useState<Suppression|null>(null),[selectedCase,setSelectedCase]=useState<AnalysisCase|null>(null);
 const [threshold,setThreshold]=useState(60),[result,setResult]=useState<Record<string,number>|null>(null);
 const [windowForm,setWindowForm]=useState({name:'게임 이벤트 영향',pattern:'',hours:24,reason:'공지된 게임 이벤트/점검에 따른 예상 시장 변동',enabled:true});
 const [caseForm,setCaseForm]=useState({title:'',status:'OPEN',priority:'P2',owner:'',summary:''});
 const toggle=async(id:number,enabled:boolean)=>{await fetch(`${apiBase}/rules/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled})});reload()};
 const backtest=async()=>{const r=await fetch(`${apiBase}/backtests`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({riskThreshold:threshold})});setResult((await r.json()).result)};
 const openNewWindow=()=>{setSelectedWindow(null);setWindowForm({name:'게임 이벤트 영향',pattern:'',hours:24,reason:'공지된 게임 이벤트/점검에 따른 예상 시장 변동',enabled:true});setSuppressOpen(true)};
 const openWindow=(w:Suppression)=>{setSelectedWindow(w);setWindowForm({name:w.name,pattern:w.item_pattern||'',hours:Math.max(1,Math.ceil((new Date(w.ends_at).getTime()-Date.now())/3600000)),reason:w.reason,enabled:w.enabled});setSuppressOpen(true)};
 const saveWindow=async()=>{const start=selectedWindow?new Date(selectedWindow.starts_at):new Date(),end=new Date(Date.now()+windowForm.hours*3600000);await fetch(`${apiBase}/suppressions${selectedWindow?`/${selectedWindow.id}`:''}`,{method:selectedWindow?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:windowForm.name,itemPattern:windowForm.pattern||null,startsAt:start.toISOString(),endsAt:end.toISOString(),reason:windowForm.reason,enabled:windowForm.enabled})});setSuppressOpen(false);reload()};
 const deleteWindow=async()=>{if(!selectedWindow||!window.confirm(`'${selectedWindow.name}' 억제 구간을 삭제할까요?`))return;await fetch(`${apiBase}/suppressions/${selectedWindow.id}`,{method:'DELETE'});setSuppressOpen(false);reload()};
 const openCase=(c:AnalysisCase)=>{setSelectedCase(c);setCaseForm({title:c.title,status:c.status,priority:c.priority,owner:c.owner||'',summary:c.summary||''})};
 const saveCase=async()=>{if(!selectedCase)return;await fetch(`${apiBase}/cases/${selectedCase.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(caseForm)});setSelectedCase(null);reload()};
 const deleteCase=async()=>{if(!selectedCase||!window.confirm(`'${selectedCase.title}' 조사 케이스를 삭제할까요?`))return;await fetch(`${apiBase}/cases/${selectedCase.id}`,{method:'DELETE'});setSelectedCase(null);reload()};
 return <AppShell active="/rules"><PageTitle eyebrow="DETECTION ENGINE" title="탐지 규칙" description="규칙 변경 전 영향도를 검증하고 정상 이벤트 구간을 분리합니다." action={<div className="title-actions"><button className="ghost-button" onClick={openNewWindow}>억제 구간 등록</button><button onClick={()=>setBacktestOpen(true)}>백테스트 실행</button></div>}/>
 <section className="rule-page-grid">{(data?.rules??[]).map(rule=><article className="rule-card" key={rule.id}><header><span>RULE {String(rule.id).padStart(2,'0')} · v{rule.version}</span><button className={rule.enabled?'toggle on':'toggle'} onClick={()=>toggle(rule.id,!rule.enabled)}><i/></button></header><h2>{rule.name}</h2><p>{rule.description}</p><div className="threshold-list">{Object.entries(rule.thresholds).map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong></div>)}</div><footer><span className={rule.enabled?'enabled':'disabled'}>{rule.enabled?'ACTIVE':'DISABLED'}</span><button onClick={()=>setBacktestOpen(true)}>영향도 확인 →</button></footer></article>)}</section>
 <section className="operations-grid"><article className="panel ops-panel"><div className="panel-head"><div><h2>활성 억제 구간</h2><p>행을 눌러 내용을 확인하거나 수정할 수 있습니다.</p></div><button className="text-button" onClick={openNewWindow}>등록 +</button></div><div className="compact-list interactive-list">{(data?.suppressions??[]).map(w=><button key={w.id} onClick={()=>openWindow(w)}><span className="health-dot suppressed"/><p><strong>{w.name}</strong><small>{w.item_pattern||'전체 아이템'} · {w.reason}</small></p><time>{new Date(w.ends_at).toLocaleString('ko-KR')}</time><b>보기 ›</b></button>)}{!data?.suppressions.length&&<div className="empty compact">등록된 억제 구간이 없습니다.</div>}</div></article>
 <article className="panel ops-panel"><div className="panel-head"><div><h2>조사 케이스</h2><p>행을 눌러 담당자·상태·메모를 관리합니다.</p></div><a href="/alerts">알림 보기 →</a></div><div className="compact-list interactive-list">{(data?.cases??[]).map(c=><button key={c.id} onClick={()=>openCase(c)}><span className={`case-priority ${c.priority.toLowerCase()}`}>{c.priority}</span><p><strong>{c.title}</strong><small>{c.item_name} · {c.owner||'미배정'}</small></p><span className="status-pill investigating">{c.status}</span><b>보기 ›</b></button>)}{!data?.cases.length&&<div className="empty compact">생성된 조사 케이스가 없습니다.</div>}</div></article></section>
 <Modal open={suppressOpen} onClose={()=>setSuppressOpen(false)} title={selectedWindow?'억제 구간 상세·수정':'게임 이벤트 억제 구간 등록'}><div className="modal-body"><p className="modal-copy">억제는 탐지를 삭제하지 않고 정상 변동으로 예상되는 신호를 조사 큐에서 구분합니다.</p><div className="modal-form single"><label>구간 이름<input value={windowForm.name} onChange={e=>setWindowForm({...windowForm,name:e.target.value})}/></label><label>아이템 패턴<input value={windowForm.pattern} onChange={e=>setWindowForm({...windowForm,pattern:e.target.value})} placeholder="비워두면 전체 아이템"/></label><label>판정 근거<textarea value={windowForm.reason} onChange={e=>setWindowForm({...windowForm,reason:e.target.value})}/></label><label>남은 지속 시간<input type="number" min="1" value={windowForm.hours} onChange={e=>setWindowForm({...windowForm,hours:Number(e.target.value)})}/></label><label className="check-label"><input type="checkbox" checked={windowForm.enabled} onChange={e=>setWindowForm({...windowForm,enabled:e.target.checked})}/> 활성 상태</label></div><footer className="modal-actions split">{selectedWindow?<button className="danger-button" onClick={deleteWindow}>삭제</button>:<span/>}<div><button className="secondary" onClick={()=>setSuppressOpen(false)}>취소</button><button onClick={saveWindow}>{selectedWindow?'변경 저장':'억제 구간 등록'}</button></div></footer></div></Modal>
 <Modal open={!!selectedCase} onClose={()=>setSelectedCase(null)} title="조사 케이스 상세·수정"><div className="modal-body">{selectedCase&&<div className="case-context"><span className={`case-priority ${selectedCase.priority.toLowerCase()}`}>{selectedCase.priority}</span><div><strong>{selectedCase.item_name}</strong><small>Risk {selectedCase.risk_score} · {selectedCase.severity}</small></div></div>}<div className="modal-form"><label className="full">케이스 제목<input value={caseForm.title} onChange={e=>setCaseForm({...caseForm,title:e.target.value})}/></label><label>상태<select value={caseForm.status} onChange={e=>setCaseForm({...caseForm,status:e.target.value})}><option>OPEN</option><option>IN_PROGRESS</option><option>RESOLVED</option><option>CLOSED</option></select></label><label>우선순위<select value={caseForm.priority} onChange={e=>setCaseForm({...caseForm,priority:e.target.value})}><option>P1</option><option>P2</option><option>P3</option></select></label><label>담당자<input value={caseForm.owner} onChange={e=>setCaseForm({...caseForm,owner:e.target.value})} placeholder="미배정"/></label><label className="full">조사 요약<textarea value={caseForm.summary} onChange={e=>setCaseForm({...caseForm,summary:e.target.value})} placeholder="조사 내용과 결론을 기록하세요."/></label></div><footer className="modal-actions split"><button className="danger-button" onClick={deleteCase}>삭제</button><div><button className="secondary" onClick={()=>setSelectedCase(null)}>취소</button><button onClick={saveCase}>변경 저장</button></div></footer></div></Modal>
 <Modal open={backtestOpen} onClose={()=>setBacktestOpen(false)} title="최근 7일 백테스트"><div className="modal-body"><p className="modal-copy">설정한 Risk 기준이 과거 신호를 얼마나 알림으로 만들었는지 확인합니다.</p><div className="backtest-control"><label>Risk 기준<input type="number" min="0" max="100" value={threshold} onChange={e=>setThreshold(Number(e.target.value))}/></label><button onClick={backtest}>분석 실행</button></div>{result&&<div className="result-grid"><p><small>전체 신호</small><strong>{result.total}</strong></p><p><small>기준 통과</small><strong>{result.matched}</strong></p><p><small>영향 아이템</small><strong>{result.affected_items}</strong></p><p><small>평균 신뢰도</small><strong>{result.confidence}%</strong></p></div>}</div></Modal>
 </AppShell>;
}
