'use client';
import { useMemo, useState } from 'react';
import { ColumnDef, flexRender, getCoreRowModel, getSortedRowModel, SortingState, useReactTable } from '@tanstack/react-table';
import { apiBase, OpsAlert, Severity } from '../lib';
import { AppShell, Modal, PageTitle, useOperations } from '../ui';
export default function AlertsPage(){
 const {data,error,reload}=useOperations(); const [severity,setSeverity]=useState<'all'|Severity>('all'); const [status,setStatus]=useState('all'); const [selected,setSelected]=useState<OpsAlert|null>(null); const [form,setForm]=useState({status:'NEW',assignedTo:'',resolutionReason:'',analystNote:''}); const [actionForm,setActionForm]=useState({actionType:'MONITOR',targetTeam:'SECURITY',note:''});
 const [sorting,setSorting]=useState<SortingState>([{id:'risk',desc:true}]);
 const rows=useMemo(()=>(data?.alerts??[]).filter(a=>(severity==='all'||a.severity===severity)&&(status==='all'||a.status===status)),[data,severity,status]);
 const columns=useMemo<ColumnDef<OpsAlert>[]>(()=>[
  {id:'incident',header:'사건',accessorFn:a=>a.id,cell:({row})=><code>INC-{String(row.original.id).padStart(5,'0')}</code>},
  {id:'item',header:'아이템',accessorFn:a=>a.item_name,cell:({row})=><><strong>{row.original.item_name}</strong><small>{row.original.direction==='UP'?'가격 상승 방향':'가격 하락 방향'}</small></>},
  {id:'status',header:'상태',accessorFn:a=>a.status,cell:({row})=><span className={`status-pill ${row.original.status.toLowerCase()}`}>{row.original.status}</span>},
  {id:'signal',header:'탐지 신호',accessorFn:a=>a.signal,cell:({row})=><span className={`signal ${row.original.severity}`}>{row.original.signal}</span>},
  {id:'occurrences',header:'총 관측',accessorFn:a=>Number(a.occurrences),cell:({getValue})=>`${getValue<number>().toLocaleString()}회`},
  {id:'deviation',header:'편차 범위',accessorFn:a=>Number(a.max_deviation_pct),cell:({row})=><span className={row.original.direction==='UP'?'positive':'negative'}>{Number(row.original.min_deviation_pct).toFixed(1)}~{Number(row.original.max_deviation_pct).toFixed(1)}%</span>},
  {id:'confidence',header:'신뢰도',accessorFn:a=>Number(a.confidence_score),cell:({getValue})=>`${getValue<number>().toFixed(0)}%`},
  {id:'risk',header:'RISK',accessorFn:a=>Number(a.risk_score),cell:({getValue})=><b>{getValue<number>().toFixed(0)}</b>},
  {id:'activity',header:'최근 활동',accessorFn:a=>new Date(a.last_seen_at).getTime(),cell:({row})=><small>{new Date(row.original.last_seen_at).toLocaleString('ko-KR')}</small>},
 ],[]);
 const alertTable=useReactTable({data:rows,columns,state:{sorting},onSortingChange:setSorting,getCoreRowModel:getCoreRowModel(),getSortedRowModel:getSortedRowModel()});
 const open=(a:OpsAlert)=>{setSelected(a);setForm({status:a.status,assignedTo:'',resolutionReason:'',analystNote:''})};
 const save=async()=>{if(!selected)return;await fetch(`${apiBase}/alerts/${selected.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});setSelected(null);reload()};
 const makeCase=async()=>{if(!selected)return;await fetch(`${apiBase}/alerts/${selected.id}/cases`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:`${selected.item_name} 이상 징후 조사`,priority:selected.severity==='critical'?'P1':'P2',owner:form.assignedTo||null})});setSelected(null);reload()};
 const makeAction=async()=>{if(!selected)return;await fetch(`${apiBase}/response-actions`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({alertId:selected.id,...actionForm,owner:form.assignedTo||null})});setSelected(null);reload()};
 return <AppShell active="/alerts"><PageTitle eyebrow="ALERT OPERATIONS" title="이상 징후" description="중복 신호를 사건 단위로 묶고 조사 상태를 관리합니다." action={<div className="page-count"><strong>{data?.summary.activeAlerts??0}</strong><span>활성 알림</span></div>}/>
  <section className="toolbar"><div className="filters">{(['all','critical','high','medium'] as const).map(v=><button key={v} className={severity===v?'active':''} onClick={()=>setSeverity(v)}>{v==='all'?'전체 위험도':v}</button>)}</div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">전체 상태</option><option>NEW</option><option>INVESTIGATING</option><option>BENIGN</option><option>ESCALATED</option><option>CLOSED</option></select></section>
  <section className="panel route-table"><div className="table-scroll"><table><thead>{alertTable.getHeaderGroups().map(group=><tr key={group.id}>{group.headers.map(header=>{const direction=header.column.getIsSorted();return <th key={header.id}><button className={`sort-header ${direction||''}`} onClick={header.column.getToggleSortingHandler()} title={`${String(header.column.columnDef.header)} 정렬`}>{flexRender(header.column.columnDef.header,header.getContext())}<span className="sort-indicator" aria-hidden="true"><i>▲</i><i>▼</i></span></button></th>})}</tr>)}</thead><tbody>{alertTable.getRowModel().rows.map(row=><tr key={row.id} onClick={()=>open(row.original)}>{row.getVisibleCells().map(cell=><td key={cell.id}>{flexRender(cell.column.columnDef.cell,cell.getContext())}</td>)}</tr>)}</tbody></table></div>{error&&<div className="empty error-state">{error}</div>}</section>
  <Modal open={!!selected} onClose={()=>setSelected(null)} title={selected?.item_name??'사건 분석'}>{selected&&<div className="modal-body"><div className="modal-evidence"><p><small>가격 범위</small><strong>{Number(selected.min_unit_price).toLocaleString()}~{Number(selected.max_unit_price).toLocaleString()} G</strong></p><p><small>편차 범위</small><strong>{Number(selected.min_deviation_pct).toFixed(1)}~{Number(selected.max_deviation_pct).toFixed(1)}%</strong></p><p><small>가격 클러스터</small><strong>{selected.price_clusters.length}개</strong></p><p><small>총 관측</small><strong>{selected.occurrences}회</strong></p></div><section className="cluster-evidence"><div><strong>가격대별 하위 증거</strong><small>가격 구간은 사건 분리 기준이 아닌 분석 근거입니다.</small></div><div className="cluster-list">{selected.price_clusters.map(c=><p key={c.priceBucket}><span>{Number(c.minPrice).toLocaleString()}~{Number(c.maxPrice).toLocaleString()} G</span><b>{c.occurrences}회</b><em>{Number(c.minDeviation).toFixed(1)}~{Number(c.maxDeviation).toFixed(1)}%</em></p>)}</div></section><div className="modal-form"><label>상태<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>NEW</option><option>INVESTIGATING</option><option>BENIGN</option><option>ESCALATED</option><option>CLOSED</option></select></label><label>담당자<input value={form.assignedTo} onChange={e=>setForm({...form,assignedTo:e.target.value})} placeholder="분석 담당자"/></label><label>판정 사유<select value={form.resolutionReason} onChange={e=>setForm({...form,resolutionReason:e.target.value})}><option value="">미선택</option><option>GAME_EVENT</option><option>LOW_SAMPLE</option><option>EXPECTED_MARKET_MOVE</option><option>DATA_QUALITY</option><option>REQUIRES_ESCALATION</option></select></label><label className="full">분석 메모<textarea value={form.analystNote} onChange={e=>setForm({...form,analystNote:e.target.value})} placeholder="근거, 반증 자료, 다음 확인 항목"/></label></div><section className="response-action-box"><div><strong>후속 대응</strong><small>탐지 결과를 다음 운영 행동으로 연결합니다.</small></div><select value={actionForm.actionType} onChange={e=>setActionForm({...actionForm,actionType:e.target.value})}><option value="MONITOR">지속 모니터링</option><option value="REQUEST_CM_CONTEXT">CM 컨텍스트 요청</option><option value="REQUEST_DEEP_ANALYSIS">보안 심층 분석 요청</option><option value="RULE_IMPROVEMENT">탐지 규칙 개선 후보</option><option value="WATCHLIST_PRIORITY">Watchlist 우선순위 상향</option><option value="CLOSE_NORMAL">정상 시장 변동 종결</option></select><select value={actionForm.targetTeam} onChange={e=>setActionForm({...actionForm,targetTeam:e.target.value})}><option>SECURITY</option><option>CM</option><option>OPERATIONS</option></select><input value={actionForm.note} onChange={e=>setActionForm({...actionForm,note:e.target.value})} placeholder="요청 근거 또는 확인할 항목"/><button onClick={makeAction}>대응 생성</button></section><footer className="modal-actions"><button className="secondary" onClick={makeCase}>조사 케이스 생성</button><button onClick={save}>분석 결과 저장</button></footer></div>}</Modal>
 </AppShell>;
}
