'use client';
import { AppShell, MiniChart, PageTitle, useOperations } from './ui';
export default function Dashboard(){
 const {data,error}=useOperations(); const s=data?.summary;
 return <AppShell active="/"><PageTitle eyebrow="MARKET INTELLIGENCE" title="오늘의 시장 보안 브리핑" description="" action={<a className="primary-link" href="/alerts">전체 이상 징후 보기 →</a>}/>
  {error&&<div className="notice error-state">{error}</div>}
  <section className="metrics dashboard-metrics"><article className="focus-card"><div><span>활성 운영 알림</span><strong>{s?.activeAlerts??0}<small>건</small></strong></div><p>중복 신호가 정리된 분석 큐</p></article><article><div><span>고위험 알림</span><strong>{s?.highAlerts??0}<small>건</small></strong></div><p className="down">우선 조사 권장</p></article><article><div><span>수집 상태</span><strong>{s?.collectionHealthy??0}<small>/{s?.collectionTotal??0}</small></strong></div><p>최근 수집 정상 아이템</p></article><article><div><span>기준선 준비</span><strong>{s?.baselineReady??0}<small>개</small></strong></div><p>3회 이상 시계열 확보</p></article></section>
  <section className="dashboard-grid"><article className="panel dashboard-chart"><div className="panel-head"><div><h2>24시간 이상 징후</h2><p>실제 수집 시계열 기반 탐지 흐름</p></div><a href="/trends">상세 추이 →</a></div><div className="chart-kpi"><strong>{s?.activeAlerts??0}</strong><span>활성 알림</span></div><MiniChart values={(data?.trend??[]).map(v=>Number(v.alert_count))}/></article><article className="panel priority-card"><div className="panel-head"><div><h2>우선 분석 아이템</h2><p>위험도와 반복 관측 기준</p></div></div><div className="rank-list">{(data?.topItems??[]).slice(0,6).map((item,i)=><a href="/alerts" key={item.item_name}><b>{String(i+1).padStart(2,'0')}</b><p><strong>{item.item_name}</strong><small>{item.occurrences}회 반복 관측</small></p><span>{Number(item.max_risk).toFixed(0)}</span></a>)}</div></article></section>
  <section className="panel recent-alerts"><div className="panel-head"><div><h2>최근 고위험 신호</h2><p>조사가 필요한 상위 알림</p></div><a href="/alerts">전체 이상 징후 보기 →</a></div><div className="alert-cards">{(data?.alerts??[]).slice(0,4).map(a=><a href="/alerts" key={a.id}><div><span className={`signal ${a.severity}`}>{a.severity}</span><small>ALT-{String(a.id).padStart(5,'0')}</small></div><h3>{a.item_name}</h3><p>{a.signal}</p><footer><span>{a.occurrences}회 관측</span><b>RISK {Number(a.risk_score).toFixed(0)}</b></footer></a>)}</div></section>
 </AppShell>;
}
