'use client';
import { useEffect, useState } from 'react';
import { apiBase } from '../lib';
import { AppShell, Modal, PageTitle } from '../ui';
type Context={id:number;context_type:string;title:string;description:string|null;item_pattern:string|null;starts_at:string;ends_at:string;source_label:string|null;status:string;effective_status:string};
type Action={id:number;action_type:string;target_team:string|null;status:string;owner:string|null;note:string|null;item_name:string|null;risk_score:number|null;severity:string|null};
type Note={id:number;author_role:string;feedback_type:string;note:string;created_at:string;context_title:string|null;item_name:string|null};
type Collaboration={metrics:{raw_signals:number;grouped_alerts:number;benign:number;escalated:number;open_actions:number;active_contexts:number;deduplicationRate:number};contexts:Context[];actions:Action[];notes:Note[]};
const empty={contextType:'EVENT',title:'',description:'',itemPattern:'',startsAt:new Date().toISOString().slice(0,16),endsAt:new Date(Date.now()+86400000).toISOString().slice(0,16),sourceLabel:'',status:'PLANNED'};
export default function OperationsPage(){const [data,setData]=useState<Collaboration|null>(null),[contextOpen,setContextOpen]=useState(false),[selected,setSelected]=useState<Context|null>(null),[form,setForm]=useState(empty),[note,setNote]=useState(''),[action,setAction]=useState<Action|null>(null),[actionForm,setActionForm]=useState({status:'OPEN',owner:'',note:''});
 const reload=()=>fetch(`${apiBase}/collaboration/dashboard`).then(r=>r.json()).then(setData);useEffect(()=>{reload()},[]);
 const openNew=()=>{setSelected(null);setForm({...empty,startsAt:new Date().toISOString().slice(0,16),endsAt:new Date(Date.now()+86400000).toISOString().slice(0,16)});setContextOpen(true)};
 const openContext=(c:Context)=>{setSelected(c);setForm({contextType:c.context_type,title:c.title,description:c.description||'',itemPattern:c.item_pattern||'',startsAt:new Date(c.starts_at).toISOString().slice(0,16),endsAt:new Date(c.ends_at).toISOString().slice(0,16),sourceLabel:c.source_label||'',status:c.status});setContextOpen(true)};
 const save=async()=>{await fetch(`${apiBase}/contexts${selected?`/${selected.id}`:''}`,{method:selected?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,startsAt:new Date(form.startsAt).toISOString(),endsAt:new Date(form.endsAt).toISOString(),createdBy:'SECURITY'})});setContextOpen(false);reload()};
 const remove=async()=>{if(!selected||!window.confirm(`'${selected.title}' 운영 컨텍스트를 삭제할까요?`))return;await fetch(`${apiBase}/contexts/${selected.id}`,{method:'DELETE'});setContextOpen(false);reload()};
 const addNote=async()=>{if(!note.trim())return;await fetch(`${apiBase}/collaboration-notes`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({authorRole:'CM',feedbackType:'CONTEXT',note})});setNote('');reload()};
 const openAction=(a:Action)=>{setAction(a);setActionForm({status:a.status,owner:a.owner||'',note:a.note||''})};const saveAction=async()=>{if(!action)return;await fetch(`${apiBase}/response-actions/${action.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(actionForm)});setAction(null);reload()};
 const m=data?.metrics;return <AppShell active="/operations"><PageTitle eyebrow="LIVE OPERATIONS" title="운영 협업" description="던파 라이브 컨텍스트를 탐지 결과와 결합하고 CM·보안 후속 대응을 관리합니다." action={<button className="primary-button" onClick={openNew}>운영 컨텍스트 등록</button>}/>
 <section className="collab-metrics"><article><small>7일 Raw Signal</small><strong>{m?.raw_signals??0}</strong><span>규칙 평가 전 원시 신호</span></article><article><small>집계 알림</small><strong>{m?.grouped_alerts??0}</strong><span>중복 제거율 {m?.deduplicationRate??0}%</span></article><article><small>정상 변동 종결</small><strong>{m?.benign??0}</strong><span>오탐·이벤트 컨텍스트</span></article><article><small>에스컬레이션</small><strong>{m?.escalated??0}</strong><span>심층 분석 필요</span></article><article><small>열린 후속 대응</small><strong>{m?.open_actions??0}</strong><span>CM·보안 협업 큐</span></article></section>
 <section className="collab-grid"><article className="panel collab-panel"><div className="panel-head"><div><h2>게임 운영 컨텍스트</h2><p>업데이트·이벤트·점검과 탐지 신호를 교차 검토합니다.</p></div><button className="text-button" onClick={openNew}>등록 +</button></div><div className="context-list">{(data?.contexts??[]).map(c=><button key={c.id} onClick={()=>openContext(c)}><span className={`context-type ${c.context_type.toLowerCase()}`}>{c.context_type}</span><div><strong>{c.title}</strong><p>{c.description||'설명 없음'}</p><small>{c.item_pattern||'전체 아이템'} · {c.source_label||'내부 운영 정보'}</small></div><time>{new Date(c.starts_at).toLocaleDateString('ko-KR')} – {new Date(c.ends_at).toLocaleDateString('ko-KR')}</time><b>{c.effective_status}</b></button>)}{!data?.contexts.length&&<div className="empty">등록된 운영 컨텍스트가 없습니다.</div>}</div></article>
 <article className="panel collab-panel"><div className="panel-head"><div><h2>후속 대응 큐</h2><p>분석 결과가 실제 다음 행동으로 연결되는 공간입니다.</p></div><a href="/alerts">알림 분석 →</a></div><div className="action-list">{(data?.actions??[]).map(a=><button key={a.id} onClick={()=>openAction(a)}><span className={`status-pill ${a.status.toLowerCase()}`}>{a.status}</span><div><strong>{a.action_type.replaceAll('_',' ')}</strong><small>{a.item_name||'일반 운영'} · {a.target_team||'미지정'}</small></div><b>{a.owner||'미배정'} ›</b></button>)}{!data?.actions.length&&<div className="empty">알림 상세에서 후속 대응을 생성할 수 있습니다.</div>}</div></article></section>
 <section className="panel feedback-panel"><div className="panel-head"><div><h2>CM 컨텍스트 피드백</h2><p>공지·이벤트·모험가 반응 등 정량 데이터 밖의 정보를 남깁니다.</p></div></div><div className="feedback-compose"><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="예: 패키지 판매 종료 공지 이후 관련 아이템 검색량과 등록가가 상승했습니다."/><button onClick={addNote}>피드백 기록</button></div><div className="feedback-list">{(data?.notes??[]).map(n=><article key={n.id}><span>{n.author_role}</span><div><strong>{n.feedback_type.replaceAll('_',' ')}</strong><p>{n.note}</p><small>{n.context_title||n.item_name||'일반 운영'} · {new Date(n.created_at).toLocaleString('ko-KR')}</small></div></article>)}</div></section>
 <Modal open={contextOpen} onClose={()=>setContextOpen(false)} title={selected?'운영 컨텍스트 상세·수정':'운영 컨텍스트 등록'}><div className="modal-body"><div className="modal-form"><label>유형<select value={form.contextType} onChange={e=>setForm({...form,contextType:e.target.value})}><option>UPDATE</option><option>EVENT</option><option>MAINTENANCE</option><option>PACKAGE</option><option>CONTENT_RESET</option><option>OTHER</option></select></label><label className="full">제목<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="full">설명<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>영향 아이템 패턴<input value={form.itemPattern} onChange={e=>setForm({...form,itemPattern:e.target.value})} placeholder="비우면 전체"/></label><label>출처/근거<input value={form.sourceLabel} onChange={e=>setForm({...form,sourceLabel:e.target.value})} placeholder="공식 공지, CM 확인 등"/></label><label>시작<input type="datetime-local" value={form.startsAt} onChange={e=>setForm({...form,startsAt:e.target.value})}/></label><label>종료<input type="datetime-local" value={form.endsAt} onChange={e=>setForm({...form,endsAt:e.target.value})}/></label>{selected&&<label>상태<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>PLANNED</option><option>ACTIVE</option><option>ENDED</option><option>CANCELLED</option></select></label>}</div><footer className="modal-actions split">{selected?<button className="danger-button" onClick={remove}>삭제</button>:<span/>}<div><button className="secondary" onClick={()=>setContextOpen(false)}>취소</button><button onClick={save}>저장</button></div></footer></div></Modal>
 <Modal open={!!action} onClose={()=>setAction(null)} title="후속 대응 상세·수정"><div className="modal-body">{action&&<div className="case-context"><div><strong>{action.action_type.replaceAll('_',' ')}</strong><small>{action.item_name||'일반 운영'} · {action.target_team||'대상 팀 미지정'}</small></div></div>}<div className="modal-form single"><label>상태<select value={actionForm.status} onChange={e=>setActionForm({...actionForm,status:e.target.value})}><option>OPEN</option><option>IN_PROGRESS</option><option>DONE</option><option>CANCELLED</option></select></label><label>담당자<input value={actionForm.owner} onChange={e=>setActionForm({...actionForm,owner:e.target.value})}/></label><label>진행 메모<textarea value={actionForm.note} onChange={e=>setActionForm({...actionForm,note:e.target.value})}/></label></div><footer className="modal-actions"><button className="secondary" onClick={()=>setAction(null)}>취소</button><button onClick={saveAction}>변경 저장</button></footer></div></Modal>
 </AppShell>}
